### ISSUE TITLE
工具爆错

### ISSUE THREAD

**Issue by neouks** [naozibuhao/fofatools#1]
![image](https://user-images.githubusercontent.com/26845888/119776523-a20ea380-bef7-11eb-8bdf-2cec862b873b.png)
![image](https://user-images.githubusercontent.com/26845888/119776570-afc42900-bef7-11eb-8f78-2b7d162979fe.png)

**Comment by naozibuhao** [comment]
这个是fofa报错, 你看看你的标点符号是半角还是全角

**Comment by weishen250** [comment]
大佬可以留个联系方式，我们深入交流

**Comment by weishen250** [comment]
大佬，可否留个联系方式，我想跟您学习学习
